DROP TABLE IF EXISTS articles;
CREATE TABLE articles ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(100) NOT NULL, timestamps VARCHAR(255) NOT NULL, hashtags VARCHAR(255));

DROP TABLE IF EXISTS text_components;
CREATE TABLE text_components ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, article_id integer, text VARCHAR(MAX) NOT NULL);
DROP TABLE IF EXISTS comments;
CREATE TABLE comments ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer, text_component_id integer, text VARCHAR(MAX) NOT NULL, begin_index integer, end_index integer, ts timestamp);

DROP TABLE IF EXISTS image_components;
CREATE TABLE image_components ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, article_id integer, uri VARCHAR(MAX) NOT NULL);

DROP TABLE IF EXISTS survey_components;
CREATE TABLE survey_components ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, article_id integer, text VARCHAR(255) NOT NULL);
DROP TABLE IF EXISTS questions;
CREATE TABLE questions ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, survey_component_id integer, type VARCHAR(30) NOT NULL, text VARCHAR(255) NOT NULL);
DROP TABLE IF EXISTS options;
CREATE TABLE options ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, question_id integer, text VARCHAR(255) NOT NULL);
DROP TABLE IF EXISTS answers;
CREATE TABLE answers ( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer, question_id integer, option_ids VARCHAR(255) NOT NULL);